name: Luke Jordan - Ashtanga Yoga
favicon: null
layout_spectrum: 0.18395
typography_spectrum: 0.030150162521749735
title: Yoga in the tradition of Sri K Pattabhi Jois
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2bbb3'
    - '#010101'
    - '#ad7c53'
    - '#688bc1'
    - '#6e3a15'
  brandStrength: 0.45949408900924027
  lightness: 0.5754061413463205
  saturation: 0.47440243628807366
  rhythmicContrast: 0.5137065136805177
purpose: []
